# Use the official gcc image, based on debian.
# It can use version tags as well, like gcc:8.5.
# See https://hub.docker.com/_/gcc/ for more info.
image: gcc:14

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_gcc:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install catch cmake g++ libxml2 libxml2-dev zlib1g-dev
    # Remove parts of the submodule that are not used but would get into CI's
    # way when linting.
    - rm -rf ./libstriezel/archive ./libstriezel/common/graphics ./libstriezel/common/gui ./libstriezel/tests
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V

build_clang:
  image: debian:12-slim
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install catch cmake clang libxml2 libxml2-dev pkg-config zlib1g-dev
    # Remove parts of the submodule that are not used but would get into CI's
    # way when linting.
    - rm -rf ./libstriezel/archive ./libstriezel/common/graphics ./libstriezel/common/gui ./libstriezel/tests
    - export CC=clang && export CXX=clang++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V
