# Use the official gcc image, based on debian.
# It can use version tags as well, like gcc:8.5.
# See https://hub.docker.com/_/gcc/ for more info.
image: gcc:8

variables:
  GIT_SUBMODULE_STRATEGY: recursive
build:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install cmake g++ libxml2 libxml2-dev zlib1g-dev
    - git submodule update --init
    # Remove parts of the submodule that are not used but would get into CI's
    # way when linting.
    - rm -rf ./libstriezel/archive ./libstriezel/common/graphics ./libstriezel/common/gui ./libstriezel/tests
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V
