language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install libxml2 libxml2-dev -y
script:
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
