language: cpp
compiler:
  - clang
  - gcc
sudo: false
dist: xenial
addons:
  apt:
    packages:
    - freeglut3-dev
    - libarchive-dev
    - libglfw-dev
    - libunshield-dev
    - libxml2
    - libxml2-dev
    - libzip-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
