language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install freeglut3-dev libglfw-dev libxml2 libxml2-dev zlib1g-dev -y
script:
  - ./ci/cpplint.sh
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
