language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
    - freeglut3-dev
    - libglfw-dev
    - libxml2
    - libxml2-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
