language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
    - master
    - travis-ci
before_install:
  - sudo apt-get install libxml2 libxml2-dev -y
script:
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - make test
notifications:
  email: false
