language: cpp
compiler:
  - clang
  - gcc
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - freeglut3-dev
    - libarchive-dev
    - libglfw-dev
    - libunshield-dev
    - libxml2
    - libxml2-dev
    - libzip-dev
    - zlib1g-dev
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - ./ci/cpplint.sh
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
