name: GCC

on: push

jobs:
  ubuntu_gcc:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: [8, 9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-${{ matrix.version }} libxml2-dev pkg-config zlib1g-dev
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
